### ISSUE TITLE
help with exporting the repo as a notebook

### ISSUE THREAD

**Issue by pavangarlapati97** [priyavrat-misra/xrays-and-gradcam#1]
Please Share(post) this repo's code into kaggle will be a great help

**Comment by pavangarlapati97** [comment]
> Please Share(post) this repo's code into kaggle will be a great help

So That I can work with my project. I'm facing many problems while running your code in kaggle kernals 
please please share code in kaggle

**Comment by priyavrat-misra** [comment]
I did try to do it in Kaggle, but unfortunately, Kaggle doesn't allow multiple code files. They expect all of the code in just a single notebook. Doing so is often considered bad practice and makes navigation harder.
If you want to do it, you could copy the code from the different files and paste them in the kernels while taking care of the `import` statements.
Apart from that, could you share a little more about these "problems" you are having? So that I might be able to help.

**Comment by pavangarlapati97** [comment]
okay Thank you for the idea!... :)
one more Doubt-> how to manually reduce steps per epoch.?
Cause 647 steps are a bit large and it takes a lot of time to run..

**Comment by priyavrat-misra** [comment]
First things first, 647 is the number of batches, which leads to 647 weight update steps in one epoch (like you mentioned).
The number is dependent on the batch size you choose. You could decrease it by increasing the batch size but that would require higher (graphics) memory.

**Comment by pavangarlapati97** [comment]
> First things first, 647 is the number of batches, which leads to 647 weight update steps in one epoch (like you mentioned).
> The number is dependent on the batch size you choose. You could decrease it by increasing the batch size but that would require higher (graphics) memory.

okay Thanks a lot :) 💯 
Reached upto training part(accuracy=0.99,loss=0.005, ). Will try to ask if any further doubts occur

**Comment by pavangarlapati97** [comment]
Code:
densenet121 = get_densenet121(out_features=4, path='/content/COVID-19_Radiography_Dataset/lr3e-5_densenet_cuda.pth')
train_preds = get_all_preds(densenet121, train_dl)
test_preds = get_all_preds(densenet121, test_dl)

train_preds.shape, test_preds.shape



Error:
RuntimeError                              Traceback (most recent call last)
<ipython-input-46-ee940659875b> in <module>()
----> 1 densenet121 = get_densenet121(out_features=4, path='/content/COVID-19_Radiography_Dataset/lr3e-5_densenet_cuda.pth')
      2 train_preds = get_all_preds(densenet121, train_dl)
      3 test_preds = get_all_preds(densenet121, test_dl)
      4 
      5 train_preds.shape, test_preds.shape

2 frames
/usr/local/lib/python3.7/dist-packages/torch/serialization.py in __init__(self, name_or_buffer)
    240 class _open_zipfile_reader(_opener):
    241     def __init__(self, name_or_buffer) -> None:
--> 242         super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
    243 
    244 

RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted

**Comment by priyavrat-misra** [comment]
Looks like the `lr3e-5_densenet_cuda.pth` file is corrupted.
Does it show the same error when loading the other 2 models as well?

**Comment by pavangarlapati97** [comment]
> Looks like the `lr3e-5_densenet_cuda.pth` file is corrupted.
> Does it show the same error when loading the other 2 models as well?

I'm using only Densenet for my project

**Comment by priyavrat-misra** [comment]
I see.
Try loading my version of [`lr3e-5_densenet_cuda.pth`](https://drive.google.com/file/d/1-34Cb0yKPOzkQ8OtzKHMY4bmjD53cluF/view?usp=drivesdk) and check if it shows the same error.

**Comment by pavangarlapati97** [comment]
> I see.
> Try loading my version of [`lr3e-5_densenet_cuda.pth`](https://drive.google.com/file/d/1-34Cb0yKPOzkQ8OtzKHMY4bmjD53cluF/view?usp=drivesdk) and check if it shows the same error.

Will try again thank you.

**Comment by pavangarlapati97** [comment]
> I see.
> Try loading my version of [`lr3e-5_densenet_cuda.pth`](https://drive.google.com/file/d/1-34Cb0yKPOzkQ8OtzKHMY4bmjD53cluF/view?usp=drivesdk) and check if it shows the same error.

This [is](https://github.com/pavangarlapati97/pavan/blob/master/Covid_Detection.ipynb) with your lr3e-5_densenet_cuda.pth  file which i have downloaded from the link in your repo

**Comment by priyavrat-misra** [comment]
Everything looks alright ~~and would make a great r/copypasta post~~, I'm closing this issue.
