### ISSUE TITLE
Prediction

### ISSUE THREAD

**Issue by pavangarlapati97** [priyavrat-misra/xrays-and-gradcam#2]
Hi mam,

your code shows the grad cam image but it not showing what opacity it is.
please help me with this.

**Comment by pavangarlapati97** [comment]
> Hi mam,
> 
> your code shows the grad cam image but it not showing what opacity it is.
> please help me with this.

And "get_args()" the continution code related to this is missing...

**Comment by priyavrat-misra** [comment]
Firstly, I'm not a "mam". I'm a guy.
Secondly, I didn't get your question. If you are talking about inference then check `overlay_cam.py`.

**Comment by pavangarlapati97** [comment]
> Firstly, I'm not a "mam". I'm a guy.
> Secondly, I didn't get your question. If you are talking about inference then check `overlay_cam.py`.

sorry ,
I'm very new to deep learning
I have seen overlay_cam.py but you haven't used it any where if you have used to predict or classify the image please share that code too.

**Comment by pavangarlapati97** [comment]
> Firstly, I'm not a "mam". I'm a guy.
> Secondly, I didn't get your question. If you are talking about inference then check `overlay_cam.py`.

when I try to run it
Eror:
usage: GradCAM on Chest X-Rays [-h] [-i IMAGE_PATH]
                               [-l {covid_19,lung_opacity,normal,pneumonia}]
                               -m {densenet121} [-o OUTPUT_PATH]
GradCAM on Chest X-Rays: error: the following arguments are required: -m/--model
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2890: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

**Comment by pavangarlapati97** [comment]
> > Firstly, I'm not a "mam". I'm a guy.
> > Secondly, I didn't get your question. If you are talking about inference then check `overlay_cam.py`.
> 
> when I try to run it
> Error:
> usage: GradCAM on Chest X-Rays [-h] [-i IMAGE_PATH]
> [-l {covid_19,lung_opacity,normal,pneumonia}]
> -m {densenet121} [-o OUTPUT_PATH]
> GradCAM on Chest X-Rays: error: the following arguments are required: -m/--model
> An exception has occurred, use %tb to see the full traceback.
> 
> SystemExit: 2
> /usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2890: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
> warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
> 
> Where should I give those input arguments

Since
